version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1
  aws-ecs: circleci/aws-ecs@3.2

executors:
  docker_build:
    machine:
      docker_layer_caching: true
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          executor: docker_build
          registry-id: "${AWS_ECR_ACCOUNT_URL}"
          region: "${AWS_REGION}"
          repo: "php"
          tag: "${CIRCLE_SHA1}"
          path: ./
          dockerfile: ./docker/php/Dockerfile
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          family: "distributed_learn_task_definition"
          service-name: "distributed-learn-service"
          cluster-name: "distributed-learn-cluster"
          container-image-name-updates: "container=php,image-and-tag=${AWS_ECR_ACCOUNT_URL}/php:${CIRCLE_SHA1},container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}"
          requires:
            - aws-ecs/deploy-service-update
          filters:
            branches:
              only:
                - main
