version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@1.0.0
  aws-ecs: circleci/aws-ecs@0.0.6

executors:
  docker_build:
    machine:
      docker_layer_caching: true
jobs:
  aws-ecr/build_and_push_image:
    executor: docker_build
    name: "build-staging"
    account-url: "${AWS_ECR_ACCOUNT_URL}"
    region: "${AWS_REGION}"
    repo: "php"
    tag: "${CIRCLE_SHA1}"
    path: ./
    dockerfile: ./docker/php/Dockerfile
  aws-ecs/deploy_service-update:
    family: "distributed_learn_task_definition"
    service-name: "distributed-learn-service"
    cluster-name: "distributed-learn-cluster"
    container-image-name-updates: "container=php,image-and-tag=${AWS_ECR_ACCOUNT_URL}/php:${CIRCLE_SHA1},container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}"

workflows:
  version: 2
  build_deploy:
    jobs:
      - test
      - build_and_push_image:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - deploy_service_update:
          requires:
            - build-staging
          filters:
            branches:
              only:
                - main
