version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@3.2
  aws-cli: circleci/aws-cli@2.1.0
executors:
  docker_build:
    machine:
      docker_layer_caching: true


workflows:
  build-and-deploy:
    jobs:
      - build
      - build-and-push-image:
          requires:
            - build
          filters:
            branches:
              only:
                - main

      - aws-ecs/deploy-service-update:
          family: "distributed_learn_task_definition"
          service-name: "distributed-learn-service"
          cluster: "distributed-learn-cluster"
          container-image-name-updates: "container=php,image-and-tag=${AWS_ECR_ACCOUNT_URL}/php:${CIRCLE_SHA1},container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}"
          requires:
            - build-and-push-image
          filters:
            branches:
              only:
                - main
workflows:
  build-and-deploy:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          name: "php"
          executor: docker_build
          registry-id: AWS_ECR_REGISTRY_ID
          region: "ap-northeast-1"
          repo: "php"
          tag: "${CIRCLE_SHA1}"
          path: ./
          dockerfile: ./docker/php/Dockerfile

      - aws-ecr/build-and-push-image:
          name: "nginx"
          executor: docker_build
          registry-id: AWS_ECR_REGISTRY_ID
          region: "ap-northeast-1"
          repo: "nginx"
          tag: "${CIRCLE_SHA1}"
          path: ./
          dockerfile: ./docker/nginx/Dockerfile

      - aws-ecs/deploy-service-update:
          family: "distributed_learn_task_definition"
          service-name: "distributed-learn-service"
          cluster: "distributed-learn-cluster"
          container-image-name-updates: "container=php,image-and-tag=${AWS_ECR_ACCOUNT_URL}/php:${CIRCLE_SHA1},container=nginx,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}"
          requires:
            - php
            - nginx
